name: my first action
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubeuntu-latest
    steps:
      - name: print greetings
        run: echo Hellow, world
      - name: print bye
        run: good bye
